In [87]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [89]:
resume_data=pd.read_csv(r"C:\Users\adity\Resume_Classification\Resumes\Cleaned_Resumes.csv")
resume_data

Category                                     Resume_Details
0   PeopleSoft  anubhav kumar singh work globally competitive ...
1   PeopleSoft  ananda rayudu profile summary years experience...
2   PeopleSoft  peoplesoft database administrator gangareddy p...
3   PeopleSoft  classification internal murali experience summ...
4   PeopleSoft  priyanka ramadoss mountpleasant coonoor nilgir...
..         ...                                                ...
74     Workday  workday integration consultant name sri krishn...
75     Workday  seeking suitable positions workday hcm techno ...
76     Workday  workday hcm fcm name role kumar workday consul...
77     Workday  venkateswarlu workday consultant professional ...
78     Workday  vinay kumar workday functional consultant expe...

[79 rows x 2 columns]

In [91]:
x = resume_data['Resume_Details'].values
y = resume_data['Category'].values

In [93]:
from sklearn.model_selection import train_test_split

In [95]:
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=45, test_size=0.25)
x_train.shape, x_test.shape

((59,), (20,))

In [97]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [99]:
tfidf_vector = TfidfVectorizer(sublinear_tf=True,stop_words='english')

In [101]:
x_train = tfidf_vector.fit_transform(x_train)
x_test = tfidf_vector.transform(x_test)

In [103]:
x_train.shape, x_test.shape

((59, 3778), (20, 3778))

In [105]:
print(y_train),print(y_test)

['React JS Developer' 'React JS Developer' 'SQL Developer' 'Workday'
 'React JS Developer' 'Workday' 'PeopleSoft' 'PeopleSoft'
 'React JS Developer' 'Workday' 'React JS Developer' 'PeopleSoft'
 'React JS Developer' 'SQL Developer' 'Workday' 'SQL Developer' 'Workday'
 'PeopleSoft' 'React JS Developer' 'PeopleSoft' 'Workday'
 'React JS Developer' 'PeopleSoft' 'SQL Developer' 'SQL Developer'
 'PeopleSoft' 'Workday' 'Workday' 'SQL Developer' 'React JS Developer'
 'React JS Developer' 'React JS Developer' 'React JS Developer' 'Workday'
 'Workday' 'Workday' 'PeopleSoft' 'React JS Developer' 'PeopleSoft'
 'Workday' 'React JS Developer' 'Workday' 'React JS Developer'
 'PeopleSoft' 'Workday' 'PeopleSoft' 'SQL Developer' 'SQL Developer'
 'SQL Developer' 'PeopleSoft' 'Workday' 'PeopleSoft' 'Workday'
 'React JS Developer' 'Workday' 'React JS Developer' 'PeopleSoft'
 'React JS Developer' 'Workday']
['React JS Developer' 'React JS Developer' 'PeopleSoft'
 'React JS Developer' 'React JS Developer' 'P

(None, None)

## Decision Tree Clasdsifier

In [108]:
from sklearn.tree import DecisionTreeClassifier

In [110]:
model_DT = DecisionTreeClassifier(criterion='gini')

In [112]:
model_DT.fit(x_train, y_train)

DecisionTreeClassifier()

In [114]:
y_pred = model_DT.predict(x_test)

In [116]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, classification_report, precision_score, recall_score

In [118]:
accuracy_DT = accuracy_score(y_test, y_pred)

In [167]:
print('Accuracy of training set : {:.2f}'.format(model_DT.score(x_train, y_train)))
print('Accuracy of  test set    : {:.2f}'.format(model_DT.score(x_test, y_test)))

Accuracy of training set : 1.00
Accuracy of  test set    : 0.95


In [174]:
precision_DT = round(precision_score(y_test,y_pred,average = 'macro'),2)
recall_DT= round(recall_score(y_test,y_pred, average = 'macro'),2)
f1_DT = round(f1_score(y_test,y_pred, average = 'macro'),2)
accuracy_DT = round(accuracy_score(y_test,y_pred),2)

In [122]:
print("classification_report : ")
print(classification_report(y_test, y_pred))

classification_report : 
                    precision    recall  f1-score   support

        PeopleSoft       1.00      1.00      1.00         6
React JS Developer       0.86      1.00      0.92         6
     SQL Developer       1.00      0.80      0.89         5
           Workday       1.00      1.00      1.00         3

          accuracy                           0.95        20
         macro avg       0.96      0.95      0.95        20
      weighted avg       0.96      0.95      0.95        20



In [124]:
print("Confusion Matrix : ")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix : 
[[6 0 0 0]
 [0 6 0 0]
 [0 1 4 0]
 [0 0 0 3]]


## Random Forest Classifier

In [127]:
from sklearn.ensemble import RandomForestClassifier

In [129]:
model_RF = RandomForestClassifier(n_estimators=200)

In [131]:
model_RF.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200)

In [133]:
y_pred1 = model_RF.predict(x_test)

In [135]:
accuracy_RF = accuracy_score(y_test, y_pred1)

In [169]:
print('Accuracy of training set : {:.2f}'.format(model_RF.score(x_train, y_train)))
print('Accuracy of  test set    : {:.2f}'.format(model_RF.score(x_test, y_test)))

Accuracy of training set : 1.00
Accuracy of  test set    : 0.95


In [176]:
precision_RF = round(precision_score(y_test,y_pred1,average = 'macro'),2)
recall_RF = round(recall_score(y_test,y_pred1, average = 'macro'),2)
f1_RF = round(f1_score(y_test,y_pred1, average = 'macro'),2)
accuracy_RF = round(accuracy_score(y_test,y_pred1),2)

In [139]:
print("classification_report : ")
print(classification_report(y_test, y_pred1))

classification_report : 
                    precision    recall  f1-score   support

        PeopleSoft       1.00      0.83      0.91         6
React JS Developer       0.86      1.00      0.92         6
     SQL Developer       1.00      1.00      1.00         5
           Workday       1.00      1.00      1.00         3

          accuracy                           0.95        20
         macro avg       0.96      0.96      0.96        20
      weighted avg       0.96      0.95      0.95        20



In [141]:
print("Confusion Matrix : ")
print(confusion_matrix(y_test, y_pred1))

Confusion Matrix : 
[[5 1 0 0]
 [0 6 0 0]
 [0 0 5 0]
 [0 0 0 3]]


## Support Vector Machine Classifier

In [145]:
from sklearn.svm import SVC

In [147]:
model_svm = SVC()

In [149]:
model_svm.fit(x_train, y_train)

SVC()

In [151]:
y_pred2 = model_svm.predict(x_test)

In [153]:
accuracy_svm = accuracy_score(y_test, y_pred2)

In [171]:
print('Accuracy of training set : {:.2f}'.format(model_svm.score(x_train, y_train)))
print('Accuracy of  test set    : {:.2f}'.format(model_svm.score(x_test, y_test)))

Accuracy of training set : 1.00
Accuracy of  test set    : 0.90


In [178]:
precision_svm = round(precision_score(y_test,y_pred2,average = 'macro'),2)
recall_svm = round(recall_score(y_test,y_pred2, average = 'macro'),2)
f1_svm = round(f1_score(y_test,y_pred2, average = 'macro'),2)
accuracy_svm = round(accuracy_score(y_test,y_pred2),2)

In [159]:
print("classification_report : ")
print(classification_report(y_test, y_pred2))

classification_report : 
                    precision    recall  f1-score   support

        PeopleSoft       1.00      0.83      0.91         6
React JS Developer       0.75      1.00      0.86         6
     SQL Developer       1.00      0.80      0.89         5
           Workday       1.00      1.00      1.00         3

          accuracy                           0.90        20
         macro avg       0.94      0.91      0.91        20
      weighted avg       0.93      0.90      0.90        20



In [161]:
print("Confusion Matrix : ")
print(confusion_matrix(y_test, y_pred2))

Confusion Matrix : 
[[5 1 0 0]
 [0 6 0 0]
 [0 1 4 0]
 [0 0 0 3]]


In [165]:
print("Decision Tree Classifier : ",accuracy_DT)
print("Random Forest Classifier Accuracy Score : ", accuracy_RF)
print("SVM Accuracy Score : ",accuracy_svm)

Decision Tree Classifier :  0.95
Random Forest Classifier Accuracy Score :  0.95
SVM Accuracy Score :  0.9


## Model Evaluation

In [180]:
Evaluation = {"Models":["DecisionTree Classifier","RandomForest Classifier","SVM Classifier",],\
            "Train_Accuracy(%)":[model_DT.score(x_train, y_train),model_RF.score(x_train, y_train),model_svm.score(x_train, y_train)],
            "Test_Accuracy(%)":[accuracy_DT,accuracy_RF,accuracy_svm],\
            "Precision(%)":[precision_DT,precision_RF,precision_svm],\
            "Recall(%)":[recall_DT,recall_RF,recall_svm],\
            "F1-Score(%)":[f1_DT,f1_RF,f1_svm]}
table = pd.DataFrame(Evaluation)
table

Models  Train_Accuracy(%)  Test_Accuracy(%)  Precision(%)  \
0  DecisionTree Classifier                1.0              0.95          0.96   
1  RandomForest Classifier                1.0              0.95          0.96   
2           SVM Classifier                1.0              0.90          0.94   

   Recall(%)  F1-Score(%)  
0       0.95         0.95  
1       0.96         0.96  
2       0.91         0.91

In [188]:
import pickle
filename = 'ModelRF.pkl'
pickle.dump(model_RF,open(filename,'wb'))

In [186]:
filename = 'VECTOR.pkl'
pickle.dump(tfidf_vector,open(filename,'wb'))